[package]
name = "examples-amdgpu-fractal"
version = "0.1.0"
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
edition = "2018"

[[bin]]
name = "examples-amdgpu-fractal"
path = "main.rs"

[dependencies]
nd = { package = "ndarray", version = "0.13.0" }
rand = "0.7.3"
lodepng = "2.0.0"
grt-core = { version = "1.0.0", package = "geobacter-runtime-core" }
grt-amd  = { version = "1.0.0", package = "geobacter-runtime-amd" }
packed_simd = "0.3.9"
